services:
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8000
        published: 8000
    environment:
      COHERE_API_KEY: ${COHERE_API_KEY}
      MONGO_URI: ${MONGO_URI}
